Foods/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('restMenus/',views.RestMenus, name = 'restMenus'),
    path('restMenus/restMenu',views.RestMenu, name = 'restMenu'),
]

accounts/urls.py
from unicodedata import name
from django.urls import path ,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='accounts'


urlpatterns = [
    path('signin',views.signin ,name='signin'),
    path('log_out',views.log_out ,name='log_out'),
    path('productfavorites/<str:slug>',views.product_favorites ,name='product_favorites'),
    path('product-favorites',views.showproduct_favorites ,name='showproduct_favorites'),
]

foodmenu/urls.py
from django.urls import path
from . import views
from .api_view import *
app_name='foodmenu'



urlpatterns= [
    path('',views.Home, name = 'home'),
    path('booktable',views.booktable, name = 'booktable'),
    path('reservation',views.Reservation, name = 'reservation'),
    path('restaurantMenu',views.RestaurantMenu, name = 'restaurantMenu'),
    path('add_to_cart',views.add_to_cart, name = 'add_to_cart'),
    path('remove_from_Cart/<int:orderdetials_id>',views.remove_from_Cart, name = 'remove_from_Cart'),
    # path('search/', search, name='search'),


    # api
    path('api/food/list',FoodAPiList.as_view(),name='FoodAPiList'),
    path('api/food/list/<int:pk>',FoodAPiDetail.as_view(),name='FoodAPiDetail'),
    
    path('api/order/list',OrderAPiList.as_view(),name='OrderAPiList'),
    path('api/order/list/<int:order_id>/detail/', OrderDetailsByOrderIdAPIView.as_view(), name='order-detail'),
    
    path('api/add_to_cart/<int:order_id>/',AddToCartAPIView.as_view(), name = 'api_add_to_cart'),
]

payment/urls.py
from django.urls import path
from . import views
app_name='payment'
urlpatterns= [
    path('payment',views.Payment, name ='payment')
]

project/urls.py
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view
from django.urls import path,include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# schema_view = get_swagger_view(title='Pastebin API')
schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="You need to token like this == >  Authorization Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)
# this is api decomation
# http://127.0.0.1:6589/api-documentation/
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('foodmenu.urls', namespace='foodmenu')),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('',include('payment.urls')),
    path('',include('setteings.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    
    re_path(r'^api-documentation(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^api-documentation/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setteings/urls.py
from django.urls import path
from . import views
app_name = 'setteings'

urlpatterns = [
    path('aboutus',views.AboutUs, name = 'aboutus'),
]

Foods/models.py
from django.db import models

# Create your models here.

class Food(models.Model):
    name_food = models.CharField(max_length= 35) 
    contant_food = models.TextField()
    Prise_food = models.DecimalField(max_digits=5,decimal_places=2)
    image_food = models.ImageField(upload_to='photos/%y/%m/%d')
    active_food = models.BooleanField(default=True)
    

foodmenu/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import URLValidator
import uuid
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django.utils.text import slugify



# Create your models here.
class Food(models.Model):
    name_food = models.CharField(max_length= 35) 
    contant_food = models.TextField()
    Prise_food = models.DecimalField(max_digits=5,decimal_places=2)
    image_food = models.ImageField(upload_to='photos/%y/%m/%d')
    active_food = models.BooleanField(default=True)


class BookATable(models.Model):
    ChooseTableSize = models.IntegerField(default=2)
    ChooseADay = models.DateField(default=timezone.now)
    ChooseATime = models.TimeField(default=timezone.now) 
    ChooseAddressTable = models.IntegerField(default= 1,null=True)
    NotesIfAny = models.TextField(max_length=200,blank=True, null=True)
    IsTableActive = models.BooleanField(default=False)                                              
    
    
class Restaurantmenu(models.Model):
    Name = models.CharField(max_length=40)
    Price = models.DecimalField(max_digits=5,decimal_places=2)
    Image = models.ImageField(upload_to='photos/RestaurantMenu/%y/%m/%d')
    Category = models.CharField(max_length=40)
    slug = models.SlugField(blank=True ,null=True)
    def save(self,*args,**kwargs):
        self.slug= slugify(self.Name)
        super(Restaurantmenu,self).save(*args,**kwargs)
    #Assess =models.ImageField(upload_to='photos/RestaurantMenu/Assess/%y/%m/%d')
    
    def __str__(self):
        return self.Name
    
    
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    order_date= models.DateTimeField(verbose_name=_("Created At"), default=datetime.now)
    # detils = models.ManyToManyField(Restaurantmenu )
    is_finished = models.BooleanField()
    def __str__(self):
        return 'User : ' + str(self.user) + ' ==>' + 'is_finished : ' + str(self.is_finished)



class OrderDetails(models.Model):
    product = models.ForeignKey(Restaurantmenu,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    cost=models.DecimalField(max_digits=5,decimal_places=0,verbose_name=_("Cost"))
    quantity=models.IntegerField()
    class Meta:
        verbose_name = _("OrderDetail")
        verbose_name_plural = _("OrderDetails")
    def __str__(self):
        return 'User: ' +  self.order.user.username + 'Product: '+ self.product.Name + 'Order id: ' + str(self.order.id)
    # def get_absolute_url(self):
    #     return reverse("OrderDetails_detail", kwargs={"pk": self.pk})







#  This class use to check address is CharField or UrlField  
class CharOrURLField(models.CharField):
    validators = [URLValidator()]

    def get_prep_value(self, value):
        if self.is_valid_url(value):
            return value.lower()
        return value

    def is_valid_url(self, value):
        try:
            URLValidator()(value)
            return True
        except:
            return False

# class FoodDelivery(models.Model):
#     Name = models.CharField(max_length=40)
#     Phone = models.CharField(max_length=50)
#     NotesIfAny = models.TextField(max_length=100)
#     Address = CharOrURLField(max_length=255) # Char or URL field 

Foods/views.py
from django.shortcuts import render
from .models import Food
# Create your views here.


def RestMenu(request):
    # You Are In Page one Restaurant Menu
    context = {'name': 'Value from context'}
    return render(request, 'Food/RestMenu.html',context)


def RestMenus(request):
    # You Are In Page All Restaurant Menu
    data = Food.objects.all()
    context = {'food': data}
    return render(request, 'Food/RestMenus.html',context)

foodmenu/views.py
from django.shortcuts import render
from accounts.models import *
from payment.models import PageAddress
from .models import BookATable,Restaurantmenu,Order,OrderDetails
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
# from django.http import HttpResponse

from django.shortcuts import render ,redirect
from django.contrib import messages

from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.http import HttpResponseNotFound
# from.models import Checkout

# @login_required(login_url='/accounts/signin')
def add_to_cart(request):
    if request.user.is_authenticated:
        if 'product' in request.GET and 'product_price' in request.GET and 'qty' in request.GET:
            product= request.GET['product']
            qty= request.GET['qty']
            order= Order.objects.all().filter(user=request.user,is_finished=False)
            productname=Restaurantmenu.objects.get(slug=product)
            if order:
                old_order=Order.objects.get(user=request.user,is_finished=False)
                if OrderDetails.objects.all().filter(order=old_order,product=productname).exists():
                    order_detials=OrderDetails.objects.get(order=old_order,product=productname)
                    order_detials.quantity += int(qty)
                    order_detials.save()
                else:
                    order_detials=OrderDetails.objects.create(
                        product=productname,
                        order=old_order,
                        cost=productname.Price,
                        quantity=qty)
            else:
                new_order=Order()
                new_order.user=request.user
                new_order.order_date=timezone.now()
                new_order.is_finished=False
                new_order.save()
                order_detials=OrderDetails.objects.create(
                    product=productname,
                    order=new_order,
                    cost=productname.Price,
                    quantity=qty)
            messages.success(request,'Product added successfully To Cart')
            return redirect ('/restaurantMenu')
        else:
            messages.error(request,'Error To Add in Cart')
            return redirect ('restaurantMenu')
    else:
    
        messages.error(request,'You Must Be Login')
        return redirect ('/restaurantMenu')

from django.core.exceptions import ObjectDoesNotExist
def remove_from_Cart(request,orderdetials_id):
    try:
        orderdetials = OrderDetails.objects.get(id=orderdetials_id)
        if request.user.id == orderdetials.order.user.id:
            orderdetials.delete()
            return redirect('/restaurantMenu')
        else:
            return HttpResponseForbidden("You don't have permission to edit this cart.")
    except ObjectDoesNotExist:
        return HttpResponseNotFound("OrderDetails not  found.")


# Create your views here.
def Home(request):
    # You Are In Page Home
    context = {'name': 'Value from context'}
    return render(request,'food/home.html',context)

@login_required(login_url='/accounts/signin')
def booktable(request):
    # You Are In Page BookATable
    if request.method == 'POST' :
        ChooseTableSize = request.POST.get('table-size')
        ChooseADay = request.POST.get('booking-date')
        ChooseATime = request.POST.get('booking-time')
        ChooseAddressTable = request.POST.get('text-table')
        NotesIfAny = request.POST.get('text-notes')

        booking = BookATable.objects.create(
        ChooseTableSize=ChooseTableSize,
        ChooseADay=ChooseADay,
        ChooseATime=ChooseATime,
        ChooseAddressTable=ChooseAddressTable,
        NotesIfAny=NotesIfAny,)
        
        context = {'booking': booking}
        return render(request, 'food/bookatable.html',context)
    else:
        return render(request, 'food/bookatable.html')
    


@login_required(login_url='/accounts/signin')
def RestaurantMenu(request):
    # You Are In Page RestaurantMenu
    food_list = Restaurantmenu.objects.all()
    name = ""
    if 'search' in request.GET:
        food_list1 = Restaurantmenu.objects.all()
        name = request.GET['search']
        if name:
            food_list = food_list1.filter(Name__icontains=name)
    context = {'restaurantmenu': food_list}  
    return render(request, 'food/Restmenu.html',context)


@login_required(login_url='/accounts/signin')
def Reservation(request):
    # You Are In Page Reservation
    
    static_adress=Address.objects.filter(user=request.user.profile)
    existing_page_address = PageAddress.objects.filter(user=request.user, order_address__is_finished=False).last()

    if existing_page_address is not None:
        # User has already added an address for the order
        
        return redirect('/payment')
    address=None
    phone=None
    not_if_any=None
    if request.method=='POST':
        address=request.POST['address']
        phone=request.POST['phone']
        not_if_any=request.POST['not_if_any']
        order_address=Order.objects.filter(user=request.user).last()
        page_address=PageAddress(
                        user=request.user,
                        address=address,
                        phone=phone,
                        not_if_any=not_if_any,
                        order_address=order_address)
        page_address.save()
        return redirect('/payment')
    context={'static_adress':static_adress}
    return render(request,'food/reservation.html',context)










    
    # if request.method == 'POST':
    #     Name = request.POST.get('name')
    #     Address = request.POST.get('address')
    #     Phone = request.POST.get('phone')
    #     NotesIfAny = request.POST.get('text')
    #     fooddelivery = FoodDelivery.objects.create(Name=Name, Address=Address, Phone=Phone,NotesIfAny=NotesIfAny)
    #     context = {'fooddelivery': fooddelivery}
    #     return render(request,'food/reservation.html',context)
    # else:
    #     return render(request,'food/reservation.html')
    


# foreign key in Django 
# context_processors.py

foodmenu/templates/food/Reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foodmenu/Reservation.css' %}">
    <style>
      .continuer{
        background-image: url('static/img/foodmenu/image-Reservation/0.jpg');
         
      }
    </style>
    <title>Food Delivery</title>
</head>
<body>
  {% include 'navbar.html' %}

        
  
  
  <div class="continuer">
    <div class="title">
        <h2>Food Delivery</h2>
    </div>
  <div class="all-info">
    <div class="inside-info">

      <!-- Add The map here -->
      <div class="inside-info-map">
        <h3>google map Address</h3>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11529.732311296646!2d37.04902321100238!3d36.587123619598756!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152fc3e3fef7d691%3A0x98db07e36dca7312!2z2YXYt9i52YUg2KjZiNin2KjYqSDYrdmE2Kg!5e1!3m2!1sar!2s!4v1682593823562!5m2!1sar!2s"
         width="100%" height="420px" style="border:0;" allowfullscreen="" loading="lazy"
         referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
    

    
      <div id="addresses">
        <h2 class="address-title">Static Address</h2>
        <div class="inside-addresses"">
          {% for address in static_adress %}
            <address style="width: 80%;text-align: center;margin: 10px;">
              {{address.sta_address}}</address>
               <p class="cost"> cost : {{address.sta_address.cost}}</p>
              <p class="time"> time : {{address.sta_address.time}}</p>
          {% endfor %}
        </div>
        <div class="inside-addresses">
            <p id="result"></p>
        </div>
      </div>
      

    <div class="inside-info"> <section id="user-info">
      <div class="title">
        <h3>User Information</h3>
      </div>
      <form method="POST">
        {% csrf_token %}
        <label for="address">Address:</label>
        <input type="text" id="address-from" name="address" required placeholder="Your Address"/>
    
        <label for="phone">Phone:</label>
        <input type="tel" id="phone" name="phone" required placeholder="Your Phone"/>
    
        <label for="text">Notes If Any:</label>
        <input type="text" id="text" name="not_if_any" placeholder="Notes If Any"/>
    
        <div class="info-butt">
            <button type="submit">submit</button>
        </div>
    </form>
        </div>
    </section></div>
   
  </div>
</div>

  <script src="{% static 'js/foodmenu/Reservation.js' %}">

    
  </script>
    {% include 'footer.html' %}
</body>
</html>

foodmenu/templates/food/Restmenu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="images/barbecue.jpg" type="image/x-icon">
<!-- Link for font font-awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/foodmenu/Restmenu.css' %}">
<style>
    
body {
    background-image: url('static/img/foodmenu/image-Restmenu/1.jpg');
    background-repeat: no-repeat;

}
</style>
<title>Restaurant Menu</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container" style="padding-top:4.5rem;">
        <div class="fas fa-shopping-cart" id="cart-btn"></div>        
        <div class="title">
            <h2>Restaurant Menu</h2>
            <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit
                . Modi optio quis, deleniti voluptate ipsa perferendis
                 quaerat distinctio molestias quod esse sint, commodi 
                 itaque in quo ab iusto natus. Similique, quidem nisi debitis
                  neque, unde ipsam.
            </p>
            
        </div>
        
        
        <div class="content">
            <div class="list">
                <ul>
                    <li data-color=".All">All</li>
                    <li data-color=".featured">Featured</li>
                    <li data-color=".Special">Today's Special</li>
                    <li data-color=".Arrivals">New Arrivals</li><br>
                </ul>    
            </div>
            
            
            <div class="box_flex">
                {% for rest in restaurantmenu %}
                    {% if rest.Category == "Featured" %}
                        <div class="box All featured">
                            <div class="box_img">
                                <img src="{{ rest.Image.url }}" class="myImage">
                            </div>
                            <div class="text">
                                <h3>{{ rest.Name }}</h3>
                                <hr>
                                <!-- <input id="Price" class="input--style-4" type="number" name="qty" value="1" > -->
                                <input type="hidden" name="product" value="{{product_detail.slug}}">
                                <input type="hidden" name="product_price" value="{{ rest.Price }}">
                                <section id="Price">${{ rest.Price }}</section>
                                <div class="stars">
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-regular fa-star"></i>
                                </div>
                                <article>Category: {{ rest.Category }}</article>
                                <div class="btn-Add">
                                    <form action="{% url 'foodmenu:add_to_cart' %}">
                                        <input class="input--style-4" type="number" name="qty" value="1" >
                                        <input type="hidden" name="product" value="{{rest.slug}}">
                                        <input type="hidden" name="product_price" value="{{rest.Price}}">
                                        <button>Add</button>
                                    </form>
                                    
                                    
                                </div>
                            </div>
                            
                        </div>
                        
                    {% elif rest.Category == "Special" %}
                        <div class="box All Special">
                            <div class="box_img">
                                <img src="{{ rest.Image.url }}" class="myImage">
                            </div>
                            <div class="text">
                                <h3>{{ rest.Name }}</h3>
                                <hr>
                                <section id="Price">${{ rest.Price }}</section>
                                <div class="stars">
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-regular fa-star"></i>
                                </div>
                                <article>Category: {{ rest.Category }}</article>
                                <div class="btn-Add">
                                    <form action="{% url 'foodmenu:add_to_cart' %}">
                                        <input class="input--style-4" type="number" name="qty" value="1" >
                                        <input type="hidden" name="product" value="{{rest.slug}}">
                                        <input type="hidden" name="product_price" value="{{rest.Price}}">
                                        <button>Add</button>
                                    </form>
                                    
                                    
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="box All Arrivals">
                            <div class="box_img">
                                <img src="{{ rest.Image.url }}" class="myImage">
                            </div>
                            <div class="text">
                                <h3>{{ rest.Name }}</h3>
                                <hr>
                                <section id="Price">${{ rest.Price }}</section>
                                <div class="stars">
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-regular fa-star"></i>
                                </div>
                                <article>Category: {{ rest.Category }}</article>
                                <div class="btn-Add">
                                    <form action="{% url 'foodmenu:add_to_cart' %}">
                                        <input class="input--style-4" type="number" name="qty" value="1" >
                                        <input type="hidden" name="product" value="{{rest.slug}}">
                                        <input type="hidden" name="product_price" value="{{rest.Price}}">
                                        <button>Add</button>
                                    </form>
                                    
                                    
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="alert" id="alertBox"></div>
            <div class="butfood">

                    <button type="button" class="btnone" onclick="OpenPopup()">
                        <a class="baynow">Buy Now(<span id="mySpan">0</span>)</a>
                    </button>

                <div class="popup" id="popup">
                    <img src="{% static 'img/foodmenu/image-Reservation/0.jpg' %}" alt="My Image">
                    <h2>Would you like to deliver selected foods?</h2>
                    <p>If you want to connect, click Yes Otherwise press no</p>
                    <a href="{% url 'foodmenu:reservation' %}"  onclick="ClosePopup()">Yes</a>
                    <a href="{% url 'payment:payment' %}"  onclick="ClosePopup()">No</a>
                    {% comment %} w<a href="{% url 'payment:payment' %}" onclick="ClosePopup()">No</a> {% endcomment %}
                    <a onclick="ClosePopup()">Exit</a>
                </div>
            </div>
        </div>





    </div>
    <script src="{% static 'js/foodmenu/Restmenu.js' %}"></script>
    {% include 'footer.html' %}
</body>
</html>

foodmenu/templates/food/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foodmenu/stylehome.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <title>Restaurant Home</title>
    <style>
        .big-bg{
            background-image: url('static/img/foodmenu/image-home/2.jpg');
        }
    </style>
</head>
<body>
    <div class="beg-info">
    <div class="info-one">
        <div>
            <div class="fa fa-solid fa-envelope"></div> 
            <span>Info@gmail.com</span>
        </div>
        <div>
            <div class="fa-solid fa-clock"></div>
            <span>Mon-Sat : 08:00- 23:00</span>
        </div>
    </div>

    <div class="info-one">
        <marquee>
            <span >lorem</span>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi eius minus ab.
        </marquee>
    </div>
    <div class="info-one">

        <div class="fas fa-shopping-cart"></div>
        <span>Cart : 0 Items - $0:00</span>
    </div>
    {% if user.is_authenticated %}
    <div class="info-one">
        <div class="info-one">
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
    {% else %}
    <div class="info-one">
        <a href="{% url 'accounts:signin' %}">Sing IN</a>
    </div>
    {% endif %}
    </div>


    <header>
        {% load static %}
        <div class="logo">
            <img src="{% static 'img/foodmenu/image-home/logo.png' %}" alt="My Image">
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'foodmenu:home' %}">Home</a></li>
                <li><a href="{% url 'foodmenu:booktable' %}">Book A Table</a></li>
                <li><a href="{% url 'foodmenu:restaurantMenu' %}">Restaurant Menu</a></li>
                <li><a href="{% url 'foodmenu:reservation' %}">Reservation</a></li>
                <li><a href="{% url 'setteings:aboutus' %}">About Us</a></li>
            </ul>
        </nav>

        <div class="link">
            <a href="{% url 'foodmenu:restaurantMenu' %}">Shop Now</a>
        </div>
    </header>
    <div class="big-bg">
        {% if user.is_authenticated %}
        <div class="Welcome">
            <h3 class="Welcome-user">Welcome dear {{user}} to our restaurant The Meal Factory We wish comfortable use</h3>
        </div>
        {% endif %}
    </div>

<script src="{% static 'js/foodmenu/home.js' %}"></script>
{% include 'footer.html' %}
</body>
</html>