Foods/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('restMenus/',views.RestMenus, name = 'restMenus'),
    path('restMenus/restMenu',views.RestMenu, name = 'restMenu'),
]

foodmenu/urls.py
from django.urls import path
from . import views
from .api_view import *
app_name='foodmenu'



urlpatterns= [
    path('',views.Home, name = 'home'),
    path('booktable',views.booktable, name = 'booktable'),
    path('reservation',views.Reservation, name = 'reservation'),
    path('restaurantMenu',views.RestaurantMenu, name = 'restaurantMenu'),
    path('add_to_cart',views.add_to_cart, name = 'add_to_cart'),
    path('remove_from_Cart/<int:orderdetials_id>',views.remove_from_Cart, name = 'remove_from_Cart'),
    # path('search/', search, name='search'),


    # api
    path('api/food/list',FoodAPiList.as_view(),name='FoodAPiList'),
    path('api/food/list/<int:pk>',FoodAPiDetail.as_view(),name='FoodAPiDetail'),
    
    path('api/order/list',OrderAPiList.as_view(),name='OrderAPiList'),
    path('api/order/list/<int:order_id>/detail/', OrderDetailsByOrderIdAPIView.as_view(), name='order-detail'),
    
    path('api/add_to_cart/<int:order_id>/',AddToCartAPIView.as_view(), name = 'api_add_to_cart'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns= [
path('',views.Home, name = 'home'),
path('bookatable',views.BookATable, name = 'bookatable'),
path('reservation',views.Reservation, name = 'reservation'),
path('aboutus',views.AboutUs, name = 'aboutus'),
path('contact',views.Contact, name = 'contact'),
]

project/urls.py
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view
from django.urls import path,include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# schema_view = get_swagger_view(title='Pastebin API')
schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="You need to token like this == >  Authorization Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)
# this is api decomation
# http://127.0.0.1:6589/api-documentation/
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('foodmenu.urls', namespace='foodmenu')),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('',include('payment.urls')),
    path('',include('setteings.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    
    re_path(r'^api-documentation(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^api-documentation/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setteings/urls.py
from django.urls import path
from . import views
app_name = 'setteings'

urlpatterns = [
    path('aboutus',views.AboutUs, name = 'aboutus'),
]

templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/footerandnavbar/footer.css' %}">
    <style>
      .footer{
        background-image: url('static/img/footerandnavbar/image-footer/footer-bg.jpg');
        background-position: left left; 
      }
    </style>
    
    <title>Footer</title>
</head>
<body>
    <footer class="footer">
        <div class="footer__container">
          <div class="footer__row">
            <div class="footer__column">
              <h3 class="footer__title">The Meat Factory</h3>
              <p class="footer__text">Lorem ipsum dolor df sididunt  
                 ut labore et dolore magna aliqua.</p>
            </div>
            <div class="footer__column">
              <h3 class="footer__title">Links</h3>
              <ul class="footer__list">
                <li><a href="{% url 'foodmenu:home' %}" class="footer__link">Home</a></li>
                <li><a href="{% url 'foodmenu:booktable' %}" class="footer__link">Book A Table</a></li>
                <li><a href="{% url 'foodmenu:restaurantMenu' %}" class="footer__link">Restaurant Menu</a></li>
                <li><a href="{% url 'foodmenu:reservation' %}" class="footer__link">Reservations</a></li>
                {% comment %} <li><a href="{% url 'setteings:aboutus' %}" class="footer__link">About Us</a></li> {% endcomment %}
               
              </ul>
            </div>
            <div class="footer__column">
              <h3 class="footer__title">Opening Hours</h3>
              <p class="footer__text">Mon - Fri: 9am - 9pm</p>
              <p class="footer__text">Sat - Sun: 10am - 8pm</p>
            </div>
            <div class="footer__column">
              <h3 class="footer__title">Location</h3>
              <p class="footer__text">123 Main St , fs1215</p>
              <p class="footer__text">New York, NY 10001</p>
            </div>
          </div>
        </div>
        <div class="footer__bottom">
          <p class="footer__text">&copy; 2023 The Meat Factory. All rights reserved</p>
        </div>
      </footer>
      
      <script src="{% static 'js/footerandnavbar/footer.js' %}"></script>
</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Link for font font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <!-- Link for file css -->
    <link rel="stylesheet" href="{% static 'css/footerandnavbar/navbar.css' %}">
    <style>
        .header {
            background-image: url('static/img/footerandnavbar/image-navbar/0.jpg');
        }
    </style>
    <title>Navbar</title>
</head>

<body>

    <!-- ==========Start Header========== -->

    <header class="header" style="position: fixed; z-index: 999;" id="header ">
        <a href="" class="logo">
            <img src="{% static 'img/footerandnavbar/image-navbar/logo.jpg' %}" alt="My Image">
        </a>

        <nav class="navbar">
            <a href="{% url 'foodmenu:home' %}">Home</a>
            <a href="{% url 'foodmenu:booktable' %}">Book A Table</a>
            <a href="{% url 'foodmenu:restaurantMenu' %}">Restaurant Menu</a>
            <a href="{% url 'foodmenu:reservation' %}">Reservation</a>
            {% comment %} <a href="{% url 'setteings:aboutus' %}">About Us</a> {% endcomment %}
        </nav>
        <div class="icons">

            <div class="fas fa-search" id="search-btn"></div>
            <div class="fas fa-shopping-cart" id="cart-btn"></div>
            <div class="fas fa-bars" id="menu-btn"></div>
        </div>
        <div class="search-form">
            <form method="GET">
                <input type="search" id="search-box" name="search" placeholder="Search Here...">
                <label for="search-box" class="fas fa-search"></label>
            </form>
        </div>

        <div class="cart-items-container">
            {% for detail in orderdetails  %}
                <div class="cart-item">
                   
                    <a href="{% url 'foodmenu:remove_from_Cart' detail.id %}"> <span class="fas fa-times"></span></a>
                    <img src="{{ detail.product.Image.url }}">
                    <div class="content">
                        <h3>name: {{detail.product}}</h3>
                        <div class="price">price: {{detail.cost}}</div>
                        <div class="price">quantity: {{detail.quantity}}</div>
                    </div>
                </div>
            {% endfor %}
            <!-- href="{% url 'foodmenu:restaurantMenu' %}"> -->
            <a href="{% url 'foodmenu:restaurantMenu' %}" class="btn-queries">Add To Cart</a>
        </div>
    </header>
    <!-- ==========Ends Header========== -->





    <script src="{% static 'js/footerandnavbar/navbar.js' %}"></script>
</body>

</html>